---
driver:
  name: docker

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: centos-6.4
- name: ubuntu-12.04

suites:
- name: default
  run_list:
    - recipe[tomcat]
  attributes: {}

- name: tomcat55
  run_list:
    - recipe[tomcat]
  attributes: {
    tomcat: { version: '55' }
  }

clusters:
  default:
    - default
