AllCops:
  Include:
    - metadata.rb
    - Gemfile
    - attributes/**/*
    - recipes/**/*
    - libraries/**/*
    - providers/**/*
    - resources/**/*
  Exclude:
    - test/**/*
    - vendor/**/*

Encoding:
  Exclude:
    - metadata.rb
    - Gemfile
